#!/usr/bin/env python3
"""
Report 13F kanban tasks that should be in Done based on current progress, and write
instructions for manual status sync. The kanban API does not expose a task-update
endpoint, so status must be updated in the UI (http://localhost:3004).

Usage:
  python scripts/kanban-update-13f-status.py
  python scripts/kanban-update-13f-status.py --api-url http://localhost:3005
"""

import argparse
import csv
import sys
from pathlib import Path

try:
    import requests
except ImportError:
    requests = None

WORKSPACE = Path(__file__).resolve().parent.parent
OUTPUT_MD = WORKSPACE / "outputs" / "kanban-13f-status-update.md"
OUTPUT_CSV = WORKSPACE / "outputs" / "kanban-13f-status-update.csv"
DEFAULT_API = "http://localhost:3005"

# Task title substrings that indicate our implemented 13F work (all should be Done)
DONE_TITLE_KEYWORDS = [
    "Epic: 13F",
    "13F Data Pipeline",
    "13F Holdings Diff",
    "13F Copycat Portfolio",
    "13F Fund Performance",
    "13F Stock Screener",
    "Combined Holdings",
    "13F Backtester",
    "13F Heat Map",
    "Dashboard integration (Option B",
]


def task_is_implemented(title: str) -> bool:
    return any(kw in (title or "") for kw in DONE_TITLE_KEYWORDS)


def main() -> int:
    ap = argparse.ArgumentParser(
        description="Report 13F tasks that should be Done and write status-sync instructions."
    )
    ap.add_argument("--api-url", default=DEFAULT_API, help="Kanban API base URL")
    args = ap.parse_args()

    if not requests:
        print("Install requests: pip install requests", file=sys.stderr)
        return 1

    url = f"{args.api_url.rstrip('/')}/api/board"
    try:
        r = requests.get(url, timeout=15)
        r.raise_for_status()
        board = r.json()
    except requests.RequestException as e:
        print(f"Failed to fetch board: {e}", file=sys.stderr)
        return 1

    projects = board.get("projects") or []
    tasks = board.get("tasks") or []
    project_names = {p["id"]: p.get("name") or "" for p in projects}

    # 13F / Copycat project IDs
    proj_ids_13f = [
        pid for pid, name in project_names.items()
        if "13F" in name or "Copycat" in project_names.get(pid, "")
    ]

    # Tasks in those projects that we consider implemented (should be Done)
    to_done = []
    for t in tasks:
        if t.get("projectId") not in proj_ids_13f:
            continue
        title = t.get("title") or ""
        if task_is_implemented(title):
            to_done.append({
                "id": t.get("id"),
                "title": title,
                "columnId": t.get("columnId"),
                "projectName": project_names.get(t.get("projectId"), ""),
            })

    # Sort by project then title
    to_done.sort(key=lambda x: (x["projectName"], x["title"]))

    # Write markdown instructions
    OUTPUT_MD.parent.mkdir(parents=True, exist_ok=True)
    with open(OUTPUT_MD, "w", encoding="utf-8") as f:
        f.write("# Kanban status sync: 13F tasks → Done\n\n")
        f.write("The kanban API does not support updating task status. Update the board in the UI.\n\n")
        f.write("**UI:** http://localhost:3004\n\n")
        f.write("## Tasks to move to Done\n\n")
        f.write("Based on current implementation (scripts, API, docs), these tasks are complete. Drag each to the **Done** column:\n\n")
        for x in to_done:
            current = x["columnId"] or "?"
            f.write(f"- **{x['title']}** (current: {current})\n")
        f.write("\n---\n")
        f.write("Generated by `scripts/kanban-update-13f-status.py`. Re-run after more progress to refresh.\n")

    # Optional CSV with board Task IDs and Column=done (for future import-update if supported)
    with open(OUTPUT_CSV, "w", encoding="utf-8", newline="") as f:
        w = csv.writer(f)
        w.writerow(["Project", "Task ID", "Title", "Column", "Priority", "Labels", "Description", "Created"])
        for x in to_done:
            w.writerow([
                x["projectName"],
                x["id"],
                x["title"],
                "done",
                "medium",
                "13f",
                "Status sync: implemented.",
                "",
            ])

    # Console summary
    not_done = [x for x in to_done if (x.get("columnId") or "").lower() != "done"]
    print(f"13F projects: {len(proj_ids_13f)}")
    print(f"Tasks that should be Done: {len(to_done)}")
    print(f"Already Done: {len(to_done) - len(not_done)}")
    print(f"To update in UI: {len(not_done)}")
    if not_done:
        print("\nMove to Done in http://localhost:3004:")
        for x in not_done:
            print(f"  - {x['title']}")
    print(f"\nInstructions written to: {OUTPUT_MD}")
    print(f"CSV (for reference): {OUTPUT_CSV}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
